export const ADD_ITNGREDIENTS = 'ADD_ITNGREDIENTS';
export const ADD_BUN = 'ADD_BUN';
export const DELETE_INGREDIEN = 'DELETE_INGREDIEN';
export const DROP_INGREDIENTS = 'DROP_INGREDIENTS';
export const RESET_ORDER = 'RESET_ORDER';